ai_app/urls.py
from django.contrib import admin
from django.urls import path, include
#import predictions.views as prediction

urlpatterns = [
    path('', include('predictions.urls')),
    path('admin/', admin.site.urls),
]

predictions/urls.py
from django.urls import path
from . import views

app_name = 'predictions'
urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('top/', views.Top.as_view(), name='top'),
    path('user_detail/<int:pk>/', views.User_detail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.User_update.as_view(), name='user_update'),
    path('user_create/', views.User_create.as_view(), name='user_create'),
    path('user_create/done', views.User_create_done.as_view(),
         name='user_create_done'),
    path('user_create/complete/<token>/',
         views.User_create_complete.as_view(), name='user_create_complete'),
]

predictions/models.py
from django.db import models
from tensorflow import keras
from keras.models import load_model
from PIL import Image
import numpy as np
import tensorflow as tf
import io
import base64


#graph = tf.get_default_graph()
graph = tf.compat.v1.get_default_graph()  # こっち使えって


class Photo(models.Model):
    image = models.ImageField(upload_to='photos')
    IMAGE_SIZE = 224  # 画像サイズ
    MODEL_FILE_PATH = 'predictions/ml_models/vgg16_transfer.h5'  # モデルファイル
    classes = ['car', 'motorbike']
    num_classes = len(classes)

    def predict(self):
        model = None
        global graph
        with graph.as_default():
            model = load_model(self.MODEL_FILE_PATH)

            img_data = self.image.read()
            img_bin = io.BytesIO(img_data)  # バイナリーデータに変換

            image = Image.open(img_bin)  # 変換後渡す＝標準入力と同じ動作
            image = image.convert('RGB').resize(
                (self.IMAGE_SIZE, self.IMAGE_SIZE))
            data = np.asarray(image) / 255.0  # 浮動小数点で正規化
            X = []
            X.append(data)
            X = np.array(X)

            result = model.predict([X])[0]
            predicted = result.argmax()
            percentage = int(result[predicted] * 100)

            return self.classes[predicted], percentage

    def image_src(self):
        with self.image.open() as img:
            base64_img = base64.b64encode(img.read()).decode()

            return 'data:' + img.file.content_type + ';base64,' + base64_img

predictions/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django import forms


class FileInputWithPreview(forms.ClearableFileInput):
    """プレビュー表示されるinput type=file"""
    template_name = 'predictions/widgets/file_input_with_preview.html'

    class Media:
        js = ['predictions/js/preview.js']

    def __init__(self, attrs=None, include_preview=False):
        super().__init__(attrs)
        if 'class' in self.attrs:
            self.attrs['class'] += 'preview-marker'
        else:
            self.attrs['class'] = 'preview-marker'
        self.include_preview = include_preview

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        context['widget'].update({
            'include_preview': self.include_preview,
        })
        return context


class Photo_form(forms.Form):
    image = forms.ImageField(widget=FileInputWithPreview())

    # image = forms.ImageField(widget=forms.FileInput(
    #    attrs={'class': 'custom-file-input'}))


User = get_user_model()


class User_update_form(forms.ModelForm):
    # ユーザー情報更新フォーム
    class Meta:
        model = User
        fields = ('username', 'email', 'last_name', 'first_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class Login_form(AuthenticationForm):
    # ログインフォーム
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class User_create_form(UserCreationForm):
    # ユーザー登録用フォーム
    email = forms.EmailField(required=True)  # メールも必須に

    class Meta:
        model = User
        fields = ('username', 'email', 'last_name', 'first_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        # 再登録時にメアドがかぶらないように
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

predictions/views.py
from django.views import generic
from django.views.generic import CreateView
from django.conf import settings
from django.http import HttpResponse, Http404, HttpResponseBadRequest
from django.template import loader
from django.template.loader import render_to_string
from django.shortcuts import render, redirect, resolve_url
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib.auth.decorators import login_required  # 関数用
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin  # クラス用
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from .forms import Photo_form, Login_form, User_update_form, User_create_form
from .models import Photo

# class ~~(LoginRequiredMixin,~~ )
@login_required
def index(request):
    # index
    template = loader.get_template('predictions/index.html')
    context = {'form': Photo_form()}
    return HttpResponse(template.render(context, request))


def predict(request):
    # リザルト表示
    if not request.method == 'POST':
        return redirect('predictions:index')

    form = Photo_form(request.POST, request.FILES)

    if not form.is_valid():
        raise ValueError('invalid form')

    photo = Photo(image=form.cleaned_data['image'])
    predict_label, percentage = photo.predict()
    template = loader.get_template('predictions/result.html')
    context = {
        'image_name': photo.image.name,
        'image_data': photo.image_src(),
        'class_label': predict_label,
        'score': percentage,
    }
    return HttpResponse(template.render(context, request))


class Top(generic.TemplateView):
    template_name = 'predictions/top.html'


class Login(LoginView):
    # ログイン
    form_class = Login_form
    template_name = 'predictions/login.html'

    # def get_success_url(self):
    #    url = self.get_redirect_url()
    #    return url or resolve_url('predictions:predict', pk=self.request.user.pk)


class Logout(LogoutView):
    # ログアウト
    template_name = 'predictions/top.html'

    def log_out(self):
        logout(self.request)


class Only_own_mixin(UserPassesTestMixin, LoginRequiredMixin):
    raise_exception = True

    def test_func(self):
        # 今ログインしてるユーザーのpkと、そのユーザー情報ページのpkが同じか、又はスーパーユーザーなら許可
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


User = get_user_model()


class User_detail(Only_own_mixin, generic.DetailView, LoginRequiredMixin):
    # ユーザ情報閲覧
    model = User
    template_name = 'predictions/user_detail.html'


class User_update(Only_own_mixin, generic.UpdateView, LoginRequiredMixin):
    # ユーザ情報更新
    model = User
    form_class = User_update_form
    template_name = 'predictions/user_update.html'

    def get_success_url(self):
        return resolve_url('predictions:user_detail', pk=self.kwargs['pk'])


class User_create(generic.CreateView):
    # ユーザ仮登録
    template_name = 'predictions/user_create.html'
    form_class = User_create_form

    def form_valid(self, form):
        # 仮登録と本登録用メールの発行.
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単
        # 退会処理も、is_activeをFalseにするだけ
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string(
            'mail_templates/subject.txt', context)
        message = render_to_string(
            'mail_templates/message.txt', context)

        user.email_user(subject, message)
        return redirect('predictions:user_create_done')


class User_create_done(generic.TemplateView):
    # ユーザ仮登録
    template_name = 'predictions/user_create_done.html'


class User_create_complete(generic.TemplateView):
    # メール内URLアクセス後のユーザ本登録
    template_name = 'predictions/user_create_complete.html'
    timeout_seconds = getattr(
        settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        # tokenが正しければ本登録.
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()

predictions/templates/predictions/base.html
<!DOCTYPE html>
<html lang='ja'>
    <head>
        <meta charset='UTF-8'>
        {%load static%}
        {%load bootstrap4%}
        {%bootstrap_css%}
        <link rel='stylesheet' type='text/css' href="{%static 'predictions/css/style.css'%}">
        {%bootstrap_javascript jquery='full'%}
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>バイク・車判定 {%block title%}{%endblock%}</title>
    </head>
    <body>
        <nav class="navbar navbar-extend-lg navbar-light bg-light">
            <a class='navbar-brand' href="{% url 'predictions:index' %}">{%block top_title%}画像判定AIアプリ{%endblock%}</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="Navber">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index'%}">管理サイト</a>
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'predictions:user_detail' user.pk %}">ユーザー情報閲覧</a>
                        <a class="nav-item nav-link" href="{% url 'predictions:user_update' user.pk %}">ユーザー情報更新</a>
                        <a style="float:left" class="nav-link" href="{% url 'predictions:logout'%}">Hi! {{request.user}} Logout?</a>
                        <a style="float:right" class="nav-item" >Now {{request.user.pk}} users active. </a>
                        {% else %}
                        <a class="nav-link" href="{% url 'predictions:login'%}">Welcome! please <b>Login</b></a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </nav>
        <div class='container'>
            {%block content%}{%endblock%}
        </div>
    </body>
</html>

predictions/templates/predictions/index.html
{% extends "predictions/base.html" %}

{% block title %}バイク・車推定アプリメニュー
{% endblock  %}

{% block content %}
<div>
    <h4 class='mt-4 mb-5 border-bottom'>バイク・車推定アプリメニュー</h4>
    <p>画像ファイルを選択してPredictボタンをクリック</p>
    <form action="{%url 'predictions:predict'%}" method='post' class='form' enctype="multipart/form-data">
        {% csrf_token %} <!-- クロスサイトリクエストフォージェリ -->
        {{ form.as_p }}
        <button type='submit' class='btn btn-primary'>Predict!</button>
        {{ form.media }}
        <img id="image-preview" style="width:15vw; float:left;">
    </form>
</div>
{% endblock  %}

predictions/templates/predictions/login.html
{% extends "predictions/base.html" %}
{%block title%}Login Page{%endblock%}
{%block top_title%}Login form{%endblock%}
{% block content %}
<form action="" method="POST">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <hr>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
                <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
                <br>
                <a href="{%url 'predictions:user_create'%}" class='btn btn-primary btn-lg btn-block'>新規登録はこちら</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

predictions/templates/predictions/result.html
{% extends "predictions/base.html" %}

{% block title %}バイク・車推定結果
{% endblock  %}

{% block content %}
<div>
    <h4 class='mt-4 mb-5 border-bottom'>バイク・車推定結果</h4>
    <table class='table'>
        <tbody>
            <tr>
                <td>ファイル名</td>
                <td>{{ image_name }} </td>
            </tr>
            <tr>
                <td>画像ファイル</td>
                <td>
                    <img style="width:30vw" class='preview-img' src={{image_data}}>
                </td>
            </tr>
            <tr>
                <td>推定ラベル</td>
                <td>{{ class_label }} </td>
            </tr>
            <tr>
                <td>推定確率</td>
                <td>{{score}} </td>
            </tr>
        </tbody>
    </table>
    <a href="{%url 'predictions:index'%}" class='btn btn-primary'>画像選択メニューに戻る</a> 

</div>
{%endblock%}

predictions/templates/predictions/top.html
{% extends "predictions/base.html" %}
{%block content%}

<a href="{%url 'predictions:login'%}" class='btn btn-success'>ログインしてね！</a> 
<a href="{%url 'predictions:user_create'%}" class='btn btn-primary'>新規登録はこちら</a> 

{% endblock%}

predictions/templates/predictions/user_create.html
{% extends "predictions/base.html" %}
{%block title%}Sign up{%endblock%}
{%block top_title%}新規登録{%endblock%}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
    <a href="{%url 'predictions:login'%}" class='btn btn-success btn-lg'>登録済み？</a> 
</form>
{% endblock %}

predictions/templates/predictions/user_create_complete.html
{% extends "predictions/base.html" %}
{%block title%}Welcome!{%endblock%}
{%block top_title%}本登録完了{%endblock%}
{% block content %}
<p>
    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'predictions:login' %}">ログイン</a>
</p>
{% endblock %}

predictions/templates/predictions/user_create_done.html
{% extends "predictions/base.html" %}
{%block title%}Sign up{%endblock%}
{%block top_title%}仮登録完了{%endblock%}
{% block content %}
<p>
    会員登録確認メールを送信しました。まだ、会員登録は完了していません。<br>
    確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。
    メールが届かない場合は、メールアドレスに間違いがある可能性があります。再度登録をお願いします。
</p>
 <a class="btn btn-primary btn-lg" href="{% url 'predictions:login' %}">ログインページ</a>
{% endblock %}

predictions/templates/predictions/user_detail.html
{% extends "predictions/base.html" %}
{%block title%}Users detail{%endblock%}
{%block top_title%}{{ user.username }}のユーザ情報{%endblock%}
{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>user_name</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th>e-mail</th>
            {%if user.email != ''%}
            <td>{{ user.email }}</td>
            {%else%}
            <td>未登録</td>
            {%endif%}
        </tr>
        <tr>
            <th>last_name</th>
            {%if user.last_name != ''%}
            <td>{{ user.last_name }}</td>
            {%else%}
            <td>未登録</td>
            {%endif%}
        </tr>
        <tr>
            <th>first_name</th>
            {%if user.first_name != ''%}
            <td>{{ user.first_name }}</td>
            {%else%}
            <td>未登録</td>
            {%endif%}
        </tr>
    </tbody>
</table>
<a href="{%url 'predictions:predict'%}" class='btn btn-primary '>戻る</a>
{% endblock %}

predictions/templates/predictions/user_update.html
{% extends "predictions/base.html" %}
{%block title%}Update details{%endblock%}
{%block top_title%}{{ user.username }}のユーザ情報更新ページ{%endblock%}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    <table class="table">
        <tbody>
            {% for field in form %}
                <tr>
                    <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                    <td>{{ field }} {{ field.errors }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-lg" >送信</button>
    <a href="{%url 'predictions:predict'%}" class="btn btn-primary btn-lg">戻る</a>
</form>
{% endblock %}